### ISSUE TITLE
Couldn't match type with `SLambda` when trying to upgrade to singletons 3.0

### ISSUE THREAD

**Issue by vmchale** [goldfirere/singletons#525]
Hello,

I am trying to upgrade [clash-wavedrom](https://github.com/vmchale/clash-wavedrom) to the latest singletons (3.0) (same use as https://github.com/goldfirere/singletons/issues/435 I think).

However, I run into the following error:

```
src/Clash/WaveDrom/Internal.hs:326:2: error:
    • Couldn't match type: SProxy p0
                           -> SSymbol n0 -> STree (WaveShape a0 n0)
                     with: SLambda f0
      Expected: SLambda f0
        Actual: Sing p0 -> Sing n0 -> Sing (WaveShape a0 n0)
    • Probable cause: ‘sWaveShapeP’ is applied to too few arguments
      In the first argument of ‘applySing’, namely ‘sWaveShapeP’
      In the first argument of ‘applySing’, namely
        ‘((applySing sWaveShapeP) sA)’
      In the second argument of ‘applySing’, namely
        ‘((applySing ((applySing sWaveShapeP) sA))
            ((applySing ((singFun1 @Show_Sym0) sShow_))
               ((applySing ((applySing ((singFun2 @(-@#@$)) (%-))) sI))
                  (sFromInteger (sing :: Sing 1)))))’
    • Relevant bindings include
        sA :: Sing t (bound at src/Clash/WaveDrom/Internal.hs:326:2)
        sIndexedDsc :: Sing t
                       -> Sing t1 -> Sing (Apply (Apply IndexedDscSym0 t) t1)
          (bound at src/Clash/WaveDrom/Internal.hs:326:2)
    |
326 | $(singletonsOnly [d|
    |  ^^^^^^^^^^^^^^^^^^^...
```

This works with singletons 2.7, but I'm afraid I can't figure out how to migrate.

**Comment by RyanGlScott** [comment]
I can certainly take a look at this later, but if you are able to split out the `singletons`-specific bits from the rest of the `clash`-related code, that would go a long way in helping me get to the bottom of what is going on here. Thanks!

**Comment by RyanGlScott** [comment]
Having taken a closer look, I don't think `singletons-3.0` is responsible for your version of `clash-wavedom` failing to compile. In fact, if I apply the following tweaks to allow your fork to compile with `singletons-2.7`:

<details>

```diff
diff --git a/clash-wavedrom.cabal b/clash-wavedrom.cabal
index d7952f5..12a3926 100644
--- a/clash-wavedrom.cabal
+++ b/clash-wavedrom.cabal
@@ -46,12 +46,14 @@ library
     , ghc-typelits-natnormalise
     , lens
     , lens-aeson
-    , singletons
-    , singletons-base
     , temporary
     , text
     , typed-process
     , vector
+  if impl(ghc >= 9.0)
+    build-depends: singletons>=3, singletons-base
+  else
+    build-depends: singletons<3
   default-language: Haskell2010

 test-suite test
diff --git a/src/Clash/WaveDrom/Internal.hs b/src/Clash/WaveDrom/Internal.hs
index b87d383..0d2cc5d 100644
--- a/src/Clash/WaveDrom/Internal.hs
+++ b/src/Clash/WaveDrom/Internal.hs
@@ -1,9 +1,11 @@
+{-# LANGUAGE CPP #-}
 {-# OPTIONS_GHC -Wno-partial-type-signatures #-}
 {-# OPTIONS_GHC -fplugin GHC.TypeLits.KnownNat.Solver #-}
 {-# OPTIONS_GHC -fplugin GHC.TypeLits.Normalise       #-}

 module Clash.WaveDrom.Internal where

+#if MIN_VERSION_singletons(3,0,0)
 import qualified Clash.Prelude                 as Clash
 import           Clash.Prelude           hiding ( (++)
                                                 , Cons
@@ -74,6 +76,70 @@ import           GHC.Generics
 import           GHC.TypeLits
 import           Unsafe.Coerce
 import Data.Aeson.Types (emptyObject)
+#else
+import qualified Clash.Prelude                 as Clash
+import           Clash.Prelude           hiding ( (++)
+                                                , Cons
+                                                , Nil
+                                                , SSymbol
+                                                , foldr1
+                                                , fromList
+                                                , replicate
+                                                , undefined
+                                                )
+import           Control.DeepSeq
+import           Control.Lens                   ( transform )
+import           Data.Aeson
+import           Data.Aeson.Encode.Pretty
+import           Data.Aeson.Lens                ( )
+import           Data.Aeson.TH                  ( Options(fieldLabelModifier)
+                                                , defaultOptions
+                                                , deriveJSON
+                                                )
+import           Data.ByteString.Lazy           ( ByteString )
+import           Data.Char                      ( toLower )
+import           Data.Coerce
+import           Data.Functor
+import           Data.Kind
+import           Data.List
+import           Data.Maybe                     ( catMaybes
+                                                , fromMaybe
+                                                )
+import           Data.Monoid                    ( Ap(..) )
+import           Data.Proxy
+import           Data.Singletons.Prelude.Enum
+import           Data.Singletons.Prelude.List   ( (%++)
+                                                , type (++)
+                                                , type (++@#@$)
+                                                , Map
+                                                , SList(SCons, SNil)
+                                                , sFoldr
+                                                , sMap
+                                                )
+import           Data.Singletons.Prelude.Num    ( type (+@#@$)
+                                                , type (-@#@$)
+                                                , SNum(..)
+                                                )
+import           Data.Singletons.Prelude.Proxy  ( SProxy(SProxy) )
+import           Data.Singletons.Prelude.Show
+import           Data.Singletons.TH      hiding ( type (<=) )
+import qualified Data.Singletons.TypeLits
+import           Data.Singletons.TypeLits       ( SSymbol(SSym) )
+import qualified Data.Text                     as T
+import           Data.Text               hiding ( foldr1
+                                                , group
+                                                , null
+                                                , replicate
+                                                )
+import           Data.Type.Equality
+import           Data.Vector                    ( fromList )
+import qualified Data.Vector                   as V
+import           Debug.Trace
+import           GHC.Generics
+import           GHC.TypeLits
+import           Unsafe.Coerce
+import Data.Aeson.Types (emptyObject)
+#endif

 ----------------------------------------------------------------
 -- The shape of WaveDrom waves
```
</details>

Then I get the same error as in https://github.com/goldfirere/singletons/issues/525#issue-1291620464 when building with `singletons-2.7`. The real culprit is the fact that you have reordered the declarations too much. You have roughly the following (with some details simplified):

```hs
{-# LANGUAGE ConstraintKinds #-}
{-# LANGUAGE CPP #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE PolyKinds #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE StandaloneKindSignatures #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
module Foo where

#if MIN_VERSION_singletons(3,0,0)
import Data.Singletons.Base.TH
import Prelude.Singletons
import GHC.TypeLits
import GHC.TypeLits.Singletons
#else
import Data.Singletons.Prelude
import Data.Singletons.TH
import Data.Singletons.TypeLits
import GHC.TypeLits
#endif

data T

class ToWave a where
  type WaveShape a :: Symbol -> T
  waveShape :: Proxy a -> SSymbol n -> Sing (WaveShape a n)

type WaveShapeP (p :: Proxy a) n = WaveShape a n
$(genDefunSymbols [''WaveShapeP])

$(singletonsOnly [d|
  indexedDsc :: ToWave a => Proxy a -> Nat -> [T]
  indexedDsc a i = if i == 0
             then []
             else waveShapeP a (show_ (i - 1)) : indexedDsc a (i-1)
  |])

type SToWave = ToWave

sWaveShapeP
  :: forall a n p
   . ToWave a
  => Sing (p :: Proxy a)
  -> Sing (n :: Symbol)
  -> Sing (WaveShape a n)
sWaveShapeP _ = waveShape (Proxy @a)
```

Note that the `singletonsOnly` declaration comes _before_ the definition of `sWaveShapeP`. This is key is the issue you're seeing, because a Template Haskell declaration can only reify definitions that appear before the declaration. During splicing, `singletonsOnly` will attempt to reify a definition named `sWaveShapeP`, but because no definition with that name appears before the TH declaration, the reification will fail.

After the reification failure, `singletonsOnly` has no way of knowing whether `sWaveShapeP` is a lambda-bound variable, for which `singletonsOnly` can generate sensible code, or whether `sWaveShapeP` is an out-of-scope identifier, for which there is no hope of generating code that will typecheck. Lacking a way to distinguish between the two cases, `singletonsOnly` falls back on the code-generation strategy for lambda-bound variables. Unfortunately, that approach doesn't work here, which is responsible for the type error you see above.

Fortunately, the fix is simple: just move the definition of `sWaveShapeP` before the TH declaration. In terms of `clash-wavedrom`, that amounts to the following patch:

```diff
diff --git a/src/Clash/WaveDrom/Internal.hs b/src/Clash/WaveDrom/Internal.hs
index b87d383..becf41f 100644
--- a/src/Clash/WaveDrom/Internal.hs
+++ b/src/Clash/WaveDrom/Internal.hs
@@ -323,6 +323,14 @@ newtype WithBits a = WithBits { unWithBits :: a }
 type WaveShapeP (p :: Proxy a) n = WaveShape a n
 $(genDefunSymbols [''WaveShapeP])

+sWaveShapeP
+  :: forall a n p
+   . ToWave a
+  => Sing (p :: Proxy a)
+  -> Sing (n :: Symbol)
+  -> Sing (WaveShape a n)
+sWaveShapeP _ = waveShape (Proxy @a)
+
 $(singletonsOnly [d|
   indexedDsc :: ToWave a => Proxy a -> Nat -> [T]
   indexedDsc a i = if i == 0
@@ -436,14 +444,6 @@ instance (KnownSymbol lName, KnownSymbol rName, ToWave l, ToWave r) => ToWave (N

 type SToWave = ToWave

-sWaveShapeP
-  :: forall a n p
-   . ToWave a
-  => Sing (p :: Proxy a)
-  -> Sing (n :: Symbol)
-  -> Sing (WaveShape a n)
-sWaveShapeP _ = waveShape (Proxy @a)
-
 -- | The positive case of the @IndexedDsc@ equation
 indexedDscPositive
   :: forall a i
```
