### ISSUE TITLE
bad interaction between Data.Type.Natural.Nat and GHC's TypeLits?

### ISSUE THREAD

**Issue by cpeikert** [goldfirere/singletons#84]
I've encountered a problem that _might_ be a bug in `singletons-1.0`.

I'm using `Data.Type.Natural`'s `Nat` (from `type-natural`) as follows:

``` haskell
singletons [d|
            newtype PrimePower = PP (Nat,Nat) deriving (Eq,Show)
            -- keeps primes in sorted order; merges duplicates
            ppMul :: PrimePower -> [PrimePower] -> [PrimePower]
            ppMul x [] = [x]
            ppMul x@(PP (p,e)) pps@((PP (p',e')):pps') =
                if p == p' then (PP (p,e+e')):pps'
                else if p <= p' then x:pps
                     else (PP (p',e')):(ppMul x pps')
           |]
```

Note the `e+e'` in the `p==p'` case.

This yields the following compilation error:

```
    The second argument of ‘Apply’ should have kind ‘(,) Nat Nat’,
      but ‘Apply (Apply Tuple2Sym0 p_aqX8) (Apply (Apply (:+$) e_aqX9) e'_aqXb)’ has kind ‘(,)
                                                                                             Nat
                                                                                             GHC.TypeLits.Nat’
    In the type ‘Apply (Apply (:$) (Apply PPSym0 (Apply (Apply Tuple2Sym0 p_aqX8) (Apply (Apply (:+$) e_aqX9) e'_aqXb)))) pps'_aqXc’
    In the family declaration for ‘Case_1627493646’
```

It looks as if `singletons` is incorrectly treating the `e+e'` argument as if it should be a `Nat` from `TypeLits`.  Is this due to some special-case TH processing that matches on the string "Nat", and if so, what can be done about it?

FWIW, this exact code compiled and worked correctly with `singletons-0.10` and `type-natural-0.2.1.0`.  The breakage is with `singletons-1.0` and `type-natural-0.2.1.1`.

(BTW, singletons is great!)
