### ISSUE TITLE
singletons doesn't build on 8.0.1 because th-desugar doesn't build :(

### ISSUE THREAD

**Issue by cartazio** [goldfirere/singletons#146]
```
Language/Haskell/TH/Desugar/Reify.hs:186:24: error:
    Not in scope: data constructor ‘FamilyD’
    Perhaps you meant ‘FamilyI’ (imported from Language.Haskell.TH.Syntax)
cabal: Leaving directory '/var/folders/py/wgp_hj9d2rl3cx48yym_ynj00000gn/T/cabal-tmp-26278/th-desugar-1.5.5'
```

**Comment by goldfirere** [comment]
Released 2.1 today.
