### PR TITLE
WIP: build on GHC 8

### PR DESCRIPTION
**Pull request by christiaanb**
This is just a work in progress (WIP) where I'm trying to build `singletons` on GHC8-rc2, against [th-desugar-1.6(~~ghc8~~master branch)](https://github.com/goldfirere/th-desugar/tree/master)

~~I'm building it using the following `stack.yaml`: https://gist.github.com/christiaanb/a77ad004bdb72dd4bdb2~~
I'm building in a normal `cabal` sandbox

Until now I got as far as the following GHC panic:

```
~/devel/singletons(ghc8) $ stack --stack-yaml stack-ghc8.yaml build
singletons-2.0.1: build

--  While building package singletons-2.0.1 using:
      /home/baaijcpr/.stack/setup-exe-cache/x86_64-linux/setup-Simple-Cabal-1.23.1.0-ghc-8.0.0.20160204 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.23.1.0 build lib:singletons --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/baaijcpr/devel/singletons/.stack-work/logs/singletons-2.0.1.log

    Preprocessing library singletons-2.0.1...
    [22 of 50] Compiling Data.Singletons.Prelude.Instances ( src/Data/Singletons/Prelude/Instances.hs, .stack-work/dist/x86_64-linux/Cabal-1.23.1.0/build/Data/Singletons/Prelude/Instances.o )
    ghc: panic! (the 'impossible' happened)
      (GHC version 8.0.0.20160204 for x86_64-unknown-linux):
    	tyConsOfType hit a hole {adve}
    
    Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug
```

I don't think I'll be able to reduce it to a minimal example so I can post in on GHC Trac.

Just to be extra clear, this is a WIP branch and is not meant to be merged (right now). See it more as a notification that I'm working on porting `singletons` to ghc8.

### CODE REVIEW

**Comment by int-index** [comment]
GHC doesn't panic anymore. This is the error I'm getting instead:

```
singletons-2.0.1: build

--  While building package singletons-2.0.1 using:
      /home/gumo/.stack/setup-exe-cache/x86_64-linux/setup-Simple-Cabal-1.23.1.0-ghc-8.0.0.20160223 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.23.1.0 build lib:singletons --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/gumo/Projects/singletons/.stack-work/logs/singletons-2.0.1.log

    Configuring singletons-2.0.1...
    Preprocessing library singletons-2.0.1...
    [22 of 50] Compiling Data.Singletons.Prelude.Instances ( src/Data/Singletons/Prelude/Instances.hs, .stack-work/dist/x86_64-linux/Cabal-1.23.1.0/build/Data/Singletons/Prelude/Instances.o )
    
    /home/gumo/Projects/singletons/src/Data/Singletons/Prelude/Instances.hs:27:3: error:
        • Expected kind ‘ghc-prim-0.5.0.0:GHC.Prim.Any’,
            but ‘arg0’ has kind ‘b’
        • In the fourth argument of ‘Let1627441598LgoSym4’, namely
            ‘arg_adrj’
          In the first argument of ‘Data.Singletons.KindOf’, namely
            ‘Let1627441598LgoSym4 l_adrg l_adrh l_adri arg_adrj’
          In the definition of data constructor ‘Let1627441598LgoSym3KindInference’
```

I'm testing this using `GHC 8.0.0.20160223`

**Comment by christiaanb** [comment]
Thanks for trying on a newer version. Other build failures were to be expected given that I never got to compile the entire package on GHC8-rc2. I'll start working on this branch/patch some more once ghc8-rc3 is released.

**Comment by christiaanb** [comment]
@int-index with ghc-8.0.0.20160406 I'm still seeing the same error as you reported... but I cannot really figure out why. Because when I copy the code from the dumped TH splice in a seperate file and do some alpha-renaming GHC accepts it. It only fails in the TH-splice...

@goldfirere On GHC-7.10.2 `make tests` fails on 3 of the 45 testsuites, specifically, the dumped splices differ from the "golden" reference. I find it had to judge if these are actual errors, or that the desugaring is now just slightly different. Could you perhaps take a look?

**Comment by christiaanb** [comment]
@goldfirere I just ran the `singletons` testsuite on the `master` branch, and the reported testsuite "failures" on GHC 7.10.2 already occur when using `th-desugar-1.5.5`. So they seem unrelated to my work to get `singletons` to work with `th-desugar-1.6` (and ghc-8).

**Comment by christiaanb** [comment]
@int-index @goldfirere https://gist.github.com/christiaanb/bc31072c7ff9de81e0a140c449297f91 is the code that fails to compile as a TH splice, but compiles just fine when it is a normal file.

When compiled as a TH splice, I still get the error @int-index reported:

```
src/Data/Singletons/Prelude/Instances.hs:27:3: error:
    • Expected kind ‘ghc-prim-0.5.0.0:GHC.Prim.Any’,
        but ‘arg0’ has kind ‘b’
    • In the fourth argument of ‘Let1627888887LgoSym4’, namely
        ‘arg_a25NE’
      In the first argument of ‘Data.Singletons.KindOf’, namely
        ‘Let1627888887LgoSym4 l_a25NB l_a25NC l_a25ND arg_a25NE’
      In the definition of data constructor ‘Let1627888887LgoSym3KindInference’
```

**Comment by int-index** [comment]
Same happens with `8.1.20160407`.

**Comment by christiaanb** [comment]
Ah, based on 
* https://ghc.haskell.org/trac/ghc/ticket/11812
* https://ghc.haskell.org/trac/ghc/ticket/11813
* https://ghc.haskell.org/trac/ghc/ticket/11814

I see @goldfirere is already working on the above issues

**Comment by deepfire** [comment]
Everybody involved is most likely perfectly aware, but just to reconfirm, the problem on `8.0.1-rc3` still is the same:
```
[22 of 50] Compiling Data.Singletons.Prelude.Instances ( src/Data/Singletons/Prelude/Instances.hs, dist/build/Data/Singletons/Prelude/Instances.o )

src/Data/Singletons/Prelude/Instances.hs:27:3: error:
    • Expected kind ‘ghc-prim-0.5.0.0:GHC.Prim.Any’,
        but ‘arg0’ has kind ‘b’
    • In the fourth argument of ‘Let1627883143LgoSym4’, namely
        ‘arg_a24j0’
      In the first argument of ‘Data.Singletons.KindOf’, namely
        ‘Let1627883143LgoSym4 l_a24iX l_a24iY l_a24iZ arg_a24j0’
      In the definition of data constructor ‘Let1627883143LgoSym3KindInference’
builder for ‘/nix/store/knzsiklgylmgqdp1qsxzhhpz1jlsxi2l-singletons-2.0.1.drv’ failed with exit code 1
```

**Comment by goldfirere** [comment]
This should be fixed in GHC HEAD.

**Comment by christiaanb** [comment]
I'll close this now, given that singletons compiles on GHC8. Thanks Richard!

**Comment by goldfirere** [comment]
@christiaanb: Many thanks for your efforts toward this. After the changes to th-desugar, it seemed easier for me to make these changes not based on your PR, I'm afraid. But I'm really quite grateful for your contribution. Still tinkering with this or that, but expect a release soon.
