### ISSUE TITLE
Can't build `singletons-th-3.0` on GHC 9

### ISSUE THREAD

**Issue by ocharles** [goldfirere/singletons#513]
When I try and build `singletons-th-3.0` I get the following compilation errors, but the Changelog suggests that 3.0 should be compatible with GHC 9:

```
Configure flags:
--prefix=/nix/store/2ma909m86irypw2ch52vj637ar33anjn-singletons-th-lib-singletons-th-3.0 lib:singletons-th --package-db=clear --package-db=/nix/store/9kk1h55r4lrdm3c6a8x6yv2sgiw45pap-singletons-th-lib-singletons-th-3.0-config/lib/ghc-9.0.2/package.conf.d --exact-configuration --dependency=singletons=singletons-3.0.1-6PuvKSShBybAJFkjCueV3T --dependency=syb=syb-0.7.2.1-KYKaNnczqa08CQ4buLVjvA --dependency=th-desugar=th-desugar-1.13-BPInHZMm8aCN4s5Lir91v --dependency=th-orphans=th-orphans-0.13.12-KB85eIamVtqIAzTlPpKlN3 --dependency=rts=rts --dependency=ghc-heap=ghc-heap-9.0.2 --dependency=ghc-prim=ghc-prim-0.7.0 --dependency=integer-gmp=integer-gmp-1.1 --dependency=base=base-4.15.1.0 --dependency=deepseq=deepseq-1.4.5.0 --dependency=array=array-0.5.4.0 --dependency=ghc-boot-th=ghc-boot-th-9.0.2 --dependency=pretty=pretty-1.1.3.6 --dependency=template-haskell=template-haskell-2.17.0.0 --dependency=ghc-bignum=ghc-bignum-1.1 --dependency=exceptions=exceptions-0.10.4 --dependency=stm=stm-2.5.0.0 --dependency=ghc-boot=ghc-boot-9.0.2 --dependency=ghc=ghc-9.0.2 --dependency=Cabal=Cabal-3.4.1.0 --dependency=array=array-0.5.4.0 --dependency=binary=binary-0.8.8.0 --dependency=bytestring=bytestring-0.10.12.1 --dependency=containers=containers-0.6.4.1 --dependency=directory=directory-1.3.6.2 --dependency=filepath=filepath-1.4.2.1 --dependency=ghc-boot=ghc-boot-9.0.2 --dependency=ghc-compact=ghc-compact-0.1.0.0 --dependency=ghc-prim=ghc-prim-0.7.0 --dependency=hpc=hpc-0.6.1.0 --dependency=mtl=mtl-2.2.2 --dependency=parsec=parsec-3.1.14.0 --dependency=process=process-1.6.13.2 --dependency=text=text-1.2.5.0 --dependency=time=time-1.9.3 --dependency=transformers=transformers-0.5.6.2 --dependency=unix=unix-2.7.2.2 --dependency=xhtml=xhtml-3000.2.2.1 --dependency=terminfo=terminfo-0.4.1.5 --with-ghc=ghc --with-ghc-pkg=ghc-pkg --with-hsc2hs=hsc2hs --with-gcc=cc --with-ld=ld.gold --ghc-option=-optl-fuse-ld=gold --ld-option=-fuse-ld=gold --with-ar=ar --with-strip=strip --disable-executable-stripping --disable-library-stripping --enable-library-profiling --disable-profiling --enable-static --enable-shared --disable-coverage --enable-library-for-ghci --profiling-detail=default --enable-split-sections
copying path '/nix/store/6j73gq5znr3l2l2pxgpzl20pvrr3m27p-hasql-lib-hasql-1.5.0.1-config' from 's3://circuithub-nix-binary-cache'...
Configuring library for singletons-th-3.0..
building
Preprocessing library for singletons-th-3.0..
Building library for singletons-th-3.0..
[ 1 of 29] Compiling Data.Singletons.TH.SuppressUnusedWarnings ( src/Data/Singletons/TH/SuppressUnusedWarnings.hs, dist/build/Data/Singletons/TH/SuppressUnusedWarnings.o, dist/build/Data/Singletons/TH/SuppressUnusedWarnings.dyn_o )
[ 2 of 29] Compiling Data.Singletons.TH.Syntax ( src/Data/Singletons/TH/Syntax.hs, dist/build/Data/Singletons/TH/Syntax.o, dist/build/Data/Singletons/TH/Syntax.dyn_o )
[ 3 of 29] Compiling Data.Singletons.TH.Util ( src/Data/Singletons/TH/Util.hs, dist/build/Data/Singletons/TH/Util.o, dist/build/Data/Singletons/TH/Util.dyn_o )
[ 4 of 29] Compiling Data.Singletons.TH.Names ( src/Data/Singletons/TH/Names.hs, dist/build/Data/Singletons/TH/Names.o, dist/build/Data/Singletons/TH/Names.dyn_o )
[ 5 of 29] Compiling Data.Singletons.TH.Options ( src/Data/Singletons/TH/Options.hs, dist/build/Data/Singletons/TH/Options.o, dist/build/Data/Singletons/TH/Options.dyn_o )
[ 6 of 29] Compiling Data.Singletons.TH.Single.Fixity ( src/Data/Singletons/TH/Single/Fixity.hs, dist/build/Data/Singletons/TH/Single/Fixity.o, dist/build/Data/Singletons/TH/Single/Fixity.dyn_o )
[ 7 of 29] Compiling Data.Singletons.TH.Promote.Type ( src/Data/Singletons/TH/Promote/Type.hs, dist/build/Data/Singletons/TH/Promote/Type.o, dist/build/Data/Singletons/TH/Promote/Type.dyn_o )
[ 8 of 29] Compiling Data.Singletons.TH.Promote.Monad ( src/Data/Singletons/TH/Promote/Monad.hs, dist/build/Data/Singletons/TH/Promote/Monad.o, dist/build/Data/Singletons/TH/Promote/Monad.dyn_o )
[ 9 of 29] Compiling Data.Singletons.TH.Single.Monad ( src/Data/Singletons/TH/Single/Monad.hs, dist/build/Data/Singletons/TH/Single/Monad.o, dist/build/Data/Singletons/TH/Single/Monad.dyn_o )
[10 of 29] Compiling Data.Singletons.TH.Single.Type ( src/Data/Singletons/TH/Single/Type.hs, dist/build/Data/Singletons/TH/Single/Type.o, dist/build/Data/Singletons/TH/Single/Type.dyn_o )
[11 of 29] Compiling Data.Singletons.TH.Promote.Defun ( src/Data/Singletons/TH/Promote/Defun.hs, dist/build/Data/Singletons/TH/Promote/Defun.o, dist/build/Data/Singletons/TH/Promote/Defun.dyn_o )
[12 of 29] Compiling Data.Singletons.TH.Single.Defun ( src/Data/Singletons/TH/Single/Defun.hs, dist/build/Data/Singletons/TH/Single/Defun.o, dist/build/Data/Singletons/TH/Single/Defun.dyn_o )
[13 of 29] Compiling Data.Singletons.TH.Single.Data ( src/Data/Singletons/TH/Single/Data.hs, dist/build/Data/Singletons/TH/Single/Data.o, dist/build/Data/Singletons/TH/Single/Data.dyn_o )

src/Data/Singletons/TH/Single/Data.hs:120:29: error:
    • Couldn't match expected type ‘DPat’
                  with actual type ‘[DPat] -> DPat’
    • Probable cause: ‘DConP’ is applied to too few arguments
      In the expression:
        DConP (singledDataConName opts cname) (map DVarP varNames)
      In the first argument of ‘DClause’, namely
        ‘[DConP (singledDataConName opts cname) (map DVarP varNames)]’
      In the second argument of ‘($)’, namely
        ‘DClause
           [DConP (singledDataConName opts cname) (map DVarP varNames)]
           (foldExp
              (DConE cname')
              (map (DAppE (DVarE fromSingName) . DVarE) varNames))’
    |
120 |           return $ DClause [DConP (singledDataConName opts cname) (map DVarP varNames)]
    |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Data/Singletons/TH/Single/Data.hs:120:68: error:
    • Couldn't match type ‘DPat’ with ‘DType’
      Expected: [DType]
        Actual: [DPat]
    • In the second argument of ‘DConP’, namely ‘(map DVarP varNames)’
      In the expression:
        DConP (singledDataConName opts cname) (map DVarP varNames)
      In the first argument of ‘DClause’, namely
        ‘[DConP (singledDataConName opts cname) (map DVarP varNames)]’
    |
120 |           return $ DClause [DConP (singledDataConName opts cname) (map DVarP varNames)]
    |                                                                    ^^^^^^^^^^^^^^^^^^

src/Data/Singletons/TH/Single/Data.hs:136:22: error:
    • Couldn't match expected type ‘DPat’
                  with actual type ‘[DPat] -> DPat’
    • Probable cause: ‘DConP’ is applied to too few arguments
      In the expression: DConP cname' varPats
      In the first argument of ‘DClause’, namely ‘[DConP cname' varPats]’
      In the second argument of ‘($)’, namely
        ‘DClause
           [DConP cname' varPats]
           (multiCase
              recursiveCalls
              (map (DConP someSingDataName . listify . DVarP) svarNames)
              (DAppE
                 (DConE someSingDataName)
                 (foldExp
                    (DConE (singledDataConName opts cname)) (map DVarE svarNames))))’
    |
136 |             DClause [DConP cname' varPats]
    |                      ^^^^^^^^^^^^^^^^^^^^

src/Data/Singletons/TH/Single/Data.hs:136:35: error:
    • Couldn't match type ‘DPat’ with ‘DType’
      Expected: [DType]
        Actual: [DPat]
    • In the second argument of ‘DConP’, namely ‘varPats’
      In the expression: DConP cname' varPats
      In the first argument of ‘DClause’, namely ‘[DConP cname' varPats]’
    |
136 |             DClause [DConP cname' varPats]
    |                                   ^^^^^^^

src/Data/Singletons/TH/Single/Data.hs:138:33: error:
    • Couldn't match type ‘[DPat] -> DPat’ with ‘DPat’
      Expected: [DPat]
        Actual: [[DPat] -> DPat]
    • In the second argument of ‘multiCase’, namely
        ‘(map (DConP someSingDataName . listify . DVarP) svarNames)’
      In the second argument of ‘DClause’, namely
        ‘(multiCase
            recursiveCalls
            (map (DConP someSingDataName . listify . DVarP) svarNames)
            (DAppE
               (DConE someSingDataName)
               (foldExp
                  (DConE (singledDataConName opts cname)) (map DVarE svarNames))))’
      In the second argument of ‘($)’, namely
        ‘DClause
           [DConP cname' varPats]
           (multiCase
              recursiveCalls
              (map (DConP someSingDataName . listify . DVarP) svarNames)
              (DAppE
                 (DConE someSingDataName)
                 (foldExp
                    (DConE (singledDataConName opts cname)) (map DVarE svarNames))))’
    |
138 |                                (map (DConP someSingDataName . listify . DVarP)
    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

src/Data/Singletons/TH/Single/Data.hs:138:63: error:
    • Couldn't match type ‘DPat’ with ‘DType’
      Expected: Name -> [DType]
        Actual: Name -> [DPat]
    • In the second argument of ‘(.)’, namely ‘listify . DVarP’
      In the first argument of ‘map’, namely
        ‘(DConP someSingDataName . listify . DVarP)’
      In the second argument of ‘multiCase’, namely
        ‘(map (DConP someSingDataName . listify . DVarP) svarNames)’
    |
138 |                                (map (DConP someSingDataName . listify . DVarP)
    |                                                               ^^^^^^^^^^^^^^^
[14 of 29] Compiling Data.Singletons.TH.Deriving.Util ( src/Data/Singletons/TH/Deriving/Util.hs, dist/build/Data/Singletons/TH/Deriving/Util.o, dist/build/Data/Singletons/TH/Deriving/Util.dyn_o )

src/Data/Singletons/TH/Deriving/Util.hs:287:29: error:
    • Couldn't match type ‘DPat’ with ‘DType’
      Expected: [DType]
        Actual: [DPat]
    • In the second argument of ‘DConP’, namely
        ‘(map DVarP vars_needed)’
      In the expression: DConP con_name (map DVarP vars_needed)
      In an equation for ‘pat’:
          pat = DConP con_name (map DVarP vars_needed)
    |
287 |   let pat = DConP con_name (map DVarP vars_needed)
    |                             ^^^^^^^^^^^^^^^^^^^^^

src/Data/Singletons/TH/Deriving/Util.hs:289:34: error:
    • Couldn't match expected type ‘DPat’
                  with actual type ‘[DPat] -> DPat’
    • Probable cause: ‘pat’ is applied to too few arguments
      In the expression: pat
      In the second argument of ‘(++)’, namely ‘[pat]’
      In the first argument of ‘DClause’, namely ‘(extra_pats ++ [pat])’
    |
289 |   pure $ DClause (extra_pats ++ [pat]) rhs
    |                                  ^^^
```

**Comment by RyanGlScott** [comment]
For some reason, your build plan includes `th-desugar-1.13`, but `singletons-th-3.0` is only meant to build with `th-desugar-1.12.*`. (See the [`.cabal` file](https://hackage.haskell.org/package/singletons-th-3.0/singletons-th.cabal).) I'm not familiar with how Nix determines build plans, but I'm tempted to blame this on Nix picking an improper build plan.

**Comment by ocharles** [comment]
Ah, nice catch! It's not actually Nix's fault - I accidentally had `allow-newer: *` in my `cabal.project` :facepalm:. Thanks for the quick response, I'll close this.
