### ISSUE TITLE
Make `singletons-th` compile with `mtl-2.3.*`

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#523]
Currently, `singletons-th` fails to build with the latest Hackage release of `mtl`:

```
$ cabal build singletons-th --constraint="mtl==2.3.*" --constraint="transformers==0.6.*" -w ghc-9.2
Build profile: -w ghc-9.2.2 -O1
In order, the following will be built (use -v for more details):
 - singletons-th-3.1 (lib) (first run)
Preprocessing library for singletons-th-3.1..
Building library for singletons-th-3.1..
[ 3 of 29] Compiling Data.Singletons.TH.Util ( src\Data\Singletons\TH\Util.hs, C:\\Users\winferno\Documents\Hacking\Haskell\singletons\dist-newstyle\build\x86_64-windows\ghc-9.2.2\singletons-th-3.1\build\Data\Singletons\TH\Util.o )

src\Data\Singletons\TH\Util.hs:345:48: error:
    Not in scope: type constructor or class ‘ExceptT’
    |
345 | newtype UnravelM a = UnravelM { runUnravelM :: ExceptT String (Reader Bool) a }
    |                                                ^^^^^^^
```

I've revised `th-desugar` on Hackage to have `mtl < 2.3` upper bounds to mitigate the damage. Given that the breakage involves `ExceptT`, we may want to first wait for a new Hackage release of `mtl` that includes a fix for haskell/mtl#117.
